#mysql
spring:
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tc?useUnicode=true&characterEncoding=UTF-8&&useSSL=true
        username: root
        password: cec


      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL:DEBUG





